const express=require("express"),fs=require("fs"),path=require("path"),QR=require("qrcode"),PDFDocument=require("pdfkit"),multer=require("multer");
const app=express(),DB=path.join(__dirname,"data.json"),upload=multer({storage:multer.memoryStorage(),limits:{fileSize:12*1024*1024}});
app.use(express.json({limit:"2mb"}));app.use(express.static(path.join(__dirname,"public")));
const read=()=>JSON.parse(fs.readFileSync(DB,"utf8")),save=d=>fs.writeFileSync(DB,JSON.stringify(d,null,2));
app.get("/api/state",(q,r)=>r.json(read()));
function sheetContext(token){try{let [year,discipline,round,pairNo,side,code]=decodeURIComponent(token||"").split("|");let d=read(),draw=d.draws.find(x=>x.discipline===discipline&&String(x.round)===String(round)&&String(x.pairNo)===String(pairNo));let g=d.groups.find(x=>x.discipline===discipline&&x.code2027===code);if(!draw||!g||String(d.year)!==String(year))return null;let expected=side==="Heim"?draw.home:draw.guest;if(expected!==code)return null;return {year:d.year,discipline,round,pairNo,side,code,club:g.club,name:g.name};}catch(e){return null}}
app.get("/api/standblatt-context/:token",(q,r)=>{let c=sheetContext(q.params.token);if(!c)return r.status(404).json({error:"Standblatt nicht gefunden"});r.json(c)});
app.post("/api/analyze-standblatt",upload.single("image"),async(q,r)=>{try{let c=sheetContext(q.body.token);if(!c)return r.status(400).json({error:"Ungültiger QR-Code / Standblatt."});if(!q.file)return r.status(400).json({error:"Bitte Foto auswählen."});if(!process.env.OPENAI_API_KEY)return r.status(500).json({error:"OPENAI_API_KEY fehlt auf Render."});let prompt=`Lies dieses ausgefüllte Amtscup-Gruppenstandblatt ${c.discipline}. Der Kontext ist bereits sicher bekannt: ${c.code}, ${c.club}, ${c.name}, Runde ${c.round}, Kombination ${c.pairNo}, ${c.side}. Extrahiere NUR die handschriftlich/ausgefüllten dynamischen Felder. Bei Feld A genau 5 Schützen. Antworte ausschließlich als JSON ohne Markdown: {"shooters":[{"name":"","year":"","gender":"","sportNo":"","result":null}],"writtenIntermediate":null,"writtenGroupTotal":null,"notes":""}. Nichts erfinden; unsicher = leer/null. gender nur lesen, niemals aus Namen ableiten.`;let body={model:"gpt-4o-mini",messages:[{role:"user",content:[{type:"text",text:prompt},{type:"image_url",image_url:{url:`data:${q.file.mimetype};base64,${q.file.buffer.toString("base64")}`}}]}],response_format:{type:"json_object"},temperature:0};let rr=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Authorization":`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify(body)});let j=await rr.json();if(!rr.ok)return r.status(rr.status).json({error:j.error?.message||"KI-Analyse fehlgeschlagen"});let out=JSON.parse(j.choices?.[0]?.message?.content||"{}");r.json({context:c,...out});}catch(e){r.status(500).json({error:"Analyse fehlgeschlagen: "+e.message})}});
app.post("/api/submissions",(q,r)=>{let c=sheetContext(q.body.token);if(!c)return r.status(400).json({error:"Ungültiges Standblatt"});let d=read();d.submissions=d.submissions||[];let x={id:Date.now(),createdAt:new Date().toISOString(),context:c,shooters:q.body.shooters||[],writtenIntermediate:q.body.writtenIntermediate??null,writtenGroupTotal:q.body.writtenGroupTotal??null,calculatedIntermediate:q.body.calculatedIntermediate??null,calculatedGroupTotal:q.body.calculatedGroupTotal??null,status:"confirmed"};d.submissions=d.submissions.filter(a=>!(a.context&&a.context.discipline===c.discipline&&String(a.context.round)===String(c.round)&&String(a.context.pairNo)===String(c.pairNo)&&a.context.side===c.side));d.submissions.push(x);save(d);r.json({ok:true,id:x.id})});
app.post("/api/groups",(q,r)=>{let d=read(),g=q.body;if(!g.club||!g.name||!g.discipline)return r.status(400).json({error:"Verein, Gruppe und Disziplin sind erforderlich."});let old=d.groups.find(x=>x.discipline===g.discipline&&x.club===g.club&&x.name===g.name)||{};g={...old,...g};if(g.registered2027===undefined)g.registered2027=false;if(!g.code2027)g.code2027="";d.groups=d.groups.filter(x=>!(x.discipline===g.discipline&&x.club===g.club&&x.name===g.name));d.groups.push(g);save(d);r.json({ok:true})});
app.post("/api/register",(q,r)=>{let d=read(),g=d.groups.find(x=>x.discipline===q.body.discipline&&x.club===q.body.club&&x.name===q.body.name);if(!g)return r.status(404).json({error:"Gruppe nicht gefunden"});g.registered2027=!!q.body.registered;if(!g.registered2027)g.code2027="";save(d);r.json({ok:true})});
app.post("/api/assign-codes",(q,r)=>{let d=read(),disc=q.body.discipline,prefix=disc==="Feld A"?"A":disc==="Pistole"?"P":"J";let a=d.groups.filter(x=>x.discipline===disc&&x.registered2027).sort((x,y)=>x.club.localeCompare(y.club,"de-CH",{sensitivity:"base"})||x.name.localeCompare(y.name,"de-CH",{sensitivity:"base"}));a.forEach((g,i)=>g.code2027=prefix+(i+1));save(d);r.json({ok:true,count:a.length})});
app.post("/api/draws",(q,r)=>{let d=read(),x=q.body;if(!x.discipline||!x.round||!x.pairNo||!x.home||!x.guest)return r.status(400).json({error:"Paarung unvollständig"});if(x.home===x.guest)return r.status(400).json({error:"Heim und Gast sind gleich."});let key=[x.discipline,x.round,x.pairNo].join("|");d.draws=d.draws.filter(a=>[a.discipline,a.round,a.pairNo].join("|")!==key);x.id=Date.now();d.draws.push(x);save(d);r.json({ok:true})});
app.delete("/api/draws/:id",(q,r)=>{let d=read();d.draws=d.draws.filter(x=>String(x.id)!==String(q.params.id));save(d);r.json({ok:true})});
app.get("/api/standblatt/:discipline/:round/:pair/:side.pdf",async(q,r)=>{let d=read(),draw=d.draws.find(x=>x.discipline===q.params.discipline&&String(x.round)===q.params.round&&String(x.pairNo)===q.params.pair);if(!draw)return r.status(404).send("Paarung nicht gefunden");let code=q.params.side==="home"?draw.home:draw.guest,g=d.groups.find(x=>x.discipline===draw.discipline&&x.code2027===code);if(!g)return r.status(404).send("Gruppe nicht gefunden");let side=q.params.side==="home"?"Heim":"Gast",token=encodeURIComponent([d.year,draw.discipline,draw.round,draw.pairNo,side,g.code2027].join("|"));let url=`${q.protocol}://${q.get("host")}/?standblatt=${token}`,qr=await QR.toDataURL(url,{margin:1,width:220});r.setHeader("Content-Type","application/pdf");let doc=new PDFDocument({size:"A4",margin:36});doc.pipe(r);doc.font("Helvetica-Bold").fontSize(17).text(`Amtscup Konolfingen Gruppenstandblatt ${draw.discipline} ${d.year}`,{align:"center"});let y=90;[["Runde",draw.round],["Kombination",`${draw.pairNo} ${side}`],["Verein",g.club],["Gruppe",`${g.code2027}  ${g.name}`]].forEach(a=>{doc.rect(36,y,250,24).stroke();doc.font("Helvetica-Bold").fontSize(11).text(a[0],42,y+7);doc.font("Helvetica").text(String(a[1]),130,y+7);y+=24});if(draw.discipline==="Feld A"){doc.font("Helvetica-Bold").text("Sportgeräte / Zuschlag",330,92);["1  Stg. 90 / 4","2  Stg. 90 Ringkorn / 4","3  Stg. 57/03 / 4","4  Stg. 57/02 / 8","5  Karabiner / 4","6  Standardgewehr / 0"].forEach((t,i)=>doc.font("Helvetica").text(t,330,112+i*17));}y=220;doc.font("Helvetica-Bold").fontSize(10).text("Name Vorname",42,y).text("Jahrgang",310,y).text("M/W",375,y).text("Sportg.",420,y).text("Resultat",485,y);y+=18;for(let i=1;i<=5;i++){doc.rect(36,y,523,52).stroke();doc.font("Helvetica").fontSize(9).text(`Schütze ${i}`,42,y+5);[300,365,410,475].forEach(x=>doc.moveTo(x,y).lineTo(x,y+52).stroke());y+=52}doc.font("Helvetica-Bold").text("Zwischentotal:",365,y+10).text("Gruppentotal:",365,y+34);doc.rect(475,y,84,52).stroke();doc.font("Helvetica").fontSize(8).text("QR-Code nach dem Wettkampf scannen und Standblatt erfassen.",36,720,{width:360});doc.image(Buffer.from(qr.split(",")[1],"base64"),445,690,{width:110});doc.end()});
app.listen(process.env.PORT||3000,()=>console.log("Amtscup 2027 V6 läuft"));
