const express=require("express"),fs=require("fs"),path=require("path"),QR=require("qrcode"),PDFDocument=require("pdfkit"),multer=require("multer");
const app=express(),DB=path.join(__dirname,"data.json"),upload=multer({storage:multer.memoryStorage(),limits:{fileSize:12*1024*1024}});
app.use(express.json({limit:"2mb"}));app.use(express.static(path.join(__dirname,"public")));
const read=()=>JSON.parse(fs.readFileSync(DB,"utf8")),save=d=>fs.writeFileSync(DB,JSON.stringify(d,null,2));
app.get("/api/state",(q,r)=>r.json(read()));
function sheetContext(token){try{let [year,discipline,round,pairNo,side,code]=decodeURIComponent(token||"").split("|");let d=read(),draw=d.draws.find(x=>x.discipline===discipline&&String(x.round)===String(round)&&String(x.pairNo)===String(pairNo));let g=d.groups.find(x=>x.discipline===discipline&&x.code2027===code);if(!draw||!g||String(d.year)!==String(year))return null;let expected=side==="Heim"?draw.home:draw.guest;if(expected!==code)return null;return {year:d.year,discipline,round,pairNo,side,code,club:g.club,name:g.name};}catch(e){return null}}
app.get("/api/standblatt-context/:token",(q,r)=>{let c=sheetContext(q.params.token);if(!c)return r.status(404).json({error:"Standblatt nicht gefunden"});r.json(c)});
app.post("/api/analyze-standblatt",upload.single("image"),async(q,r)=>{try{let c=sheetContext(q.body.token);if(!c)return r.status(400).json({error:"Ungültiger QR-Code / Standblatt."});if(!q.file)return r.status(400).json({error:"Bitte Foto auswählen."});if(!process.env.OPENAI_API_KEY)return r.status(500).json({error:"OPENAI_API_KEY fehlt auf Render."});let prompt=`Lies dieses ausgefüllte Amtscup-Gruppenstandblatt ${c.discipline}. Der Kontext ist bereits sicher bekannt: ${c.code}, ${c.club}, ${c.name}, Runde ${c.round}, Kombination ${c.pairNo}, ${c.side}. Extrahiere NUR die handschriftlich/ausgefüllten dynamischen Felder. Bei Feld A genau 5 Schützen. Antworte ausschließlich als JSON ohne Markdown: {"shooters":[{"name":"","year":"","gender":"","sportNo":"","result":null}],"writtenIntermediate":null,"writtenBonus":null,"writtenGroupTotal":null,"notes":""}. Nichts erfinden; unsicher = leer/null. gender nur lesen, niemals aus Namen ableiten.`;let body={model:"gpt-4o-mini",messages:[{role:"user",content:[{type:"text",text:prompt},{type:"image_url",image_url:{url:`data:${q.file.mimetype};base64,${q.file.buffer.toString("base64")}`}}]}],response_format:{type:"json_object"},temperature:0};let rr=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Authorization":`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify(body)});let j=await rr.json();if(!rr.ok)return r.status(rr.status).json({error:j.error?.message||"KI-Analyse fehlgeschlagen"});let out=JSON.parse(j.choices?.[0]?.message?.content||"{}");r.json({context:c,...out});}catch(e){r.status(500).json({error:"Analyse fehlgeschlagen: "+e.message})}});
app.post("/api/submissions",(q,r)=>{let c=sheetContext(q.body.token);if(!c)return r.status(400).json({error:"Ungültiges Standblatt"});let d=read();d.submissions=d.submissions||[];let x={id:Date.now(),createdAt:new Date().toISOString(),context:c,shooters:q.body.shooters||[],writtenIntermediate:q.body.writtenIntermediate??null,writtenBonus:q.body.writtenBonus??null,writtenGroupTotal:q.body.writtenGroupTotal??null,calculatedIntermediate:q.body.calculatedIntermediate??null,calculatedBonus:q.body.calculatedBonus??null,calculatedGroupTotal:q.body.calculatedGroupTotal??null,status:"confirmed"};d.submissions=d.submissions.filter(a=>!(a.context&&a.context.discipline===c.discipline&&String(a.context.round)===String(c.round)&&String(a.context.pairNo)===String(c.pairNo)&&a.context.side===c.side));d.submissions.push(x);save(d);r.json({ok:true,id:x.id})});
app.post("/api/groups",(q,r)=>{let d=read(),g=q.body;if(!g.club||!g.name||!g.discipline)return r.status(400).json({error:"Verein, Gruppe und Disziplin sind erforderlich."});let old=d.groups.find(x=>x.discipline===g.discipline&&x.club===g.club&&x.name===g.name)||{};g={...old,...g};if(g.registered2027===undefined)g.registered2027=false;if(!g.code2027)g.code2027="";d.groups=d.groups.filter(x=>!(x.discipline===g.discipline&&x.club===g.club&&x.name===g.name));d.groups.push(g);save(d);r.json({ok:true})});
app.post("/api/register",(q,r)=>{let d=read(),g=d.groups.find(x=>x.discipline===q.body.discipline&&x.club===q.body.club&&x.name===q.body.name);if(!g)return r.status(404).json({error:"Gruppe nicht gefunden"});g.registered2027=!!q.body.registered;if(!g.registered2027)g.code2027="";save(d);r.json({ok:true})});
app.post("/api/assign-codes",(q,r)=>{let d=read(),disc=q.body.discipline,prefix=disc==="Feld A"?"A":disc==="Pistole"?"P":"J";let a=d.groups.filter(x=>x.discipline===disc&&x.registered2027).sort((x,y)=>x.club.localeCompare(y.club,"de-CH",{sensitivity:"base"})||x.name.localeCompare(y.name,"de-CH",{sensitivity:"base"}));a.forEach((g,i)=>g.code2027=prefix+(i+1));save(d);r.json({ok:true,count:a.length})});
app.post("/api/draws",(q,r)=>{let d=read(),x=q.body;if(!x.discipline||!x.round||!x.pairNo||!x.home||!x.guest)return r.status(400).json({error:"Paarung unvollständig"});if(x.home===x.guest)return r.status(400).json({error:"Heim und Gast sind gleich."});let key=[x.discipline,x.round,x.pairNo].join("|");d.draws=d.draws.filter(a=>[a.discipline,a.round,a.pairNo].join("|")!==key);x.id=Date.now();d.draws.push(x);save(d);r.json({ok:true})});
app.delete("/api/draws/:id",(q,r)=>{let d=read();d.draws=d.draws.filter(x=>String(x.id)!==String(q.params.id));save(d);r.json({ok:true})});
app.get("/api/standblatt/:discipline/:round/:pair/:side.pdf",async(q,r)=>{let d=read(),draw=d.draws.find(x=>x.discipline===q.params.discipline&&String(x.round)===q.params.round&&String(x.pairNo)===q.params.pair);if(!draw)return r.status(404).send("Paarung nicht gefunden");let code=q.params.side==="home"?draw.home:draw.guest,g=d.groups.find(x=>x.discipline===draw.discipline&&x.code2027===code);if(!g)return r.status(404).send("Gruppe nicht gefunden");let side=q.params.side==="home"?"Heim":"Gast",token=encodeURIComponent([d.year,draw.discipline,draw.round,draw.pairNo,side,g.code2027].join("|"));let url=`${q.protocol}://${q.get("host")}/?standblatt=${token}`,qr=await QR.toDataURL(url,{margin:1,width:220});r.setHeader("Content-Type","application/pdf");let doc=new PDFDocument({size:"A4",margin:30});doc.pipe(r);
let logo=path.join(__dirname,"public","amtscup-logo.png");if(fs.existsSync(logo))doc.image(logo,32,27,{fit:[55,62]});
doc.font("Helvetica-Bold").fontSize(16).text(`Amtscup Konolfingen Gruppenstandblatt`,95,34,{width:440,align:"center"});doc.fontSize(13).text(`${draw.discipline} ${d.year}`,95,57,{width:440,align:"center"});
let y=95;[["Runde",draw.round],["Kombination",`${draw.pairNo} ${side}`],["Verein",g.club],["Gruppe",`${g.code2027}  ${g.name}`]].forEach(a=>{doc.rect(32,y,265,23).stroke();doc.font("Helvetica-Bold").fontSize(10).text(a[0],38,y+6);doc.font("Helvetica").text(String(a[1]),125,y+6,{width:165});y+=23});
if(draw.discipline==="Feld A"){doc.font("Helvetica-Bold").fontSize(10).text("Sportgeräte / Zuschlag",320,96);["1  Stg. 90 / 4","2  Stg. 90 Ringkorn / 4","3  Stg. 57/03 / 4","4  Stg. 57/02 / 8","5  Karabiner / 4","6  Standardgewehr / 0","7  FG / 0"].forEach((t,i)=>doc.font("Helvetica").fontSize(9).text(t,320,113+i*14));doc.font("Helvetica-Bold").fontSize(8.5).text("Wichtig: Nur Sportgerät-Nr. 1–7 eintragen.",320,214,{width:240});}
y=245;let xs=[32,282,344,382,432,492,565];doc.font("Helvetica-Bold").fontSize(8.5).text("Name Vorname",38,y).text("Jahrgang",287,y).text("M/W",350,y).text("Sportg. Nr.",386,y).text("Resultat",440,y).text("Zuschlag",500,y);y+=17;for(let i=1;i<=5;i++){doc.rect(32,y,533,47).stroke();doc.font("Helvetica").fontSize(8).text(`Schütze ${i}`,38,y+5);xs.slice(1,-1).forEach(x=>doc.moveTo(x,y).lineTo(x,y+47).stroke());y+=47}
let sy=y+8;doc.font("Helvetica-Bold").fontSize(10).text("Zwischentotal:",390,sy).text("Zuschlag:",390,sy+22).text("Gruppentotal:",390,sy+44);doc.rect(492,sy-4,73,66).stroke();doc.moveTo(492,sy+18).lineTo(565,sy+18).stroke();doc.moveTo(492,sy+40).lineTo(565,sy+40).stroke();
doc.font("Helvetica-Bold").fontSize(9).text("Ausfüllen / Erfassen",32,560);doc.font("Helvetica").fontSize(8).text("Sportgerät: nur die Nummer 1–7 gemäss Tabelle eintragen. Nach dem Wettkampf QR-Code scannen, das vollständig ausgefüllte Standblatt fotografieren und die erkannten Angaben vor dem Speichern kontrollieren.",32,576,{width:355,lineGap:2});
doc.roundedRect(32,650,355,92,5).stroke();doc.font("Helvetica-Bold").fontSize(10).text("Sponsor / Werbung",42,660);doc.font("Helvetica-Bold").fontSize(15).text("Waffenhaus Schneider",42,686,{width:335,align:"center"});doc.font("Helvetica").fontSize(7).text("Werbebereich – kann später durch einen anderen Sponsor oder eine Werbegrafik ersetzt werden.",42,718,{width:335,align:"center"});
doc.font("Helvetica-Bold").fontSize(8).text("QR-Code scannen",430,625,{width:125,align:"center"});doc.image(Buffer.from(qr.split(",")[1],"base64"),438,642,{width:110});doc.font("Helvetica").fontSize(7).text("öffnet genau dieses Standblatt zur Erfassung",420,754,{width:145,align:"center"});doc.end()});
app.listen(process.env.PORT||3000,()=>console.log("Amtscup 2027 V7 läuft"));
